### ISSUE TITLE
Using mongodb

### ISSUE THREAD

**Issue by HuHguZ** [expressjs/csurf#169]
I'm trying to use mongodb in my project, but when I get connected, I get it. I assumed that this was due to the libraries, but creating a new file and connecting the same libraries, I did not see this error, what could be the problem? text of error:

<code>internal/crypto/hash.js:62
  if (!this._handle.update(data, encoding || getDefaultEncoding()))
TypeError: Bad input string
    at Hash.update (internal/crypto/hash.js:62:21)
    at new Connection (/var/www/www-root/data/www/evebot.su/node_modules/mongodb-core/lib/connection/connection.js:170:8)
    at _createConnection (/var/www/www-root/data/www/evebot.su/node_modules/mongodb-core/lib/connection/pool.js:1316:20)
    at /var/www/www-root/data/www/evebot.su/node_modules/mongodb-core/lib/connection/pool.js:1528:15
    at waitForAuth (/var/www/www-root/data/www/evebot.su/node_modules/mongodb-core/lib/connection/pool.js:1417:40)
    at /var/www/www-root/data/www/evebot.su/node_modules/mongodb-core/lib/connection/pool.js:1425:5
    at /var/www/www-root/data/www/evebot.su/node_modules/mongodb-core/lib/connection/pool.js:1278:23
    at process._tickCallback (internal/process/next_tick.js:61:11)</code>

**Comment by dougwilson** [comment]
I believe you may have posted this in the wrong project issue tracker.
