### ISSUE TITLE
Random ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by KaiserWolfTaco** [expressjs/csurf#187]
Hello,

  We are experiencing CSRF Forbidden Errors while using the csurf package.  What is strange is it only impacts a few users out of 100s.  These users that are impacted are always the same users.

 I see the following in my log:

> ForbiddenError: invalid csrf token
    at csrf (/cme/apps/install/express_server/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/cme/apps/install/express_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:317:13)
    at /cme/apps/install/express_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:335:12)
    at next (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/cme/apps/install/express_server/node_modules/cookie-parser/index.js:71:5)
    at Layer.handle [as handle_request] (/cme/apps/install/express_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:317:13)
    at /cme/apps/install/express_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:335:12)
    at next (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:275:10)
    at methodOverride (/cme/apps/install/express_server/node_modules/method-override/index.js:79:5)
    at Layer.handle [as handle_request] (/cme/apps/install/express_server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:317:13)
    at /cme/apps/install/express_server/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:335:12)
    at next (/cme/apps/install/express_server/node_modules/express/lib/router/index.js:275:10)
    at internalNext (/cme/apps/install/express_server/node_modules/helmet/index.js:47:33)
    at xXssProtection (/cme/apps/install/express_server/node_modules/x-xss-protection/index.js:26:7)
    at internalNext (/cme/apps/install/express_server/node_modules/helmet/index.js:51:7)
    at nosniff (/cme/apps/install/express_server/node_modules/dont-sniff-mimetype/index.js:4:5)

Here is my current setup:

```
var app = express();

// express configurations
app.enable("strict routing");
app.set("views", __dirname + "/views");
app.set('view engine', 'pug');
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(helmet());
app.use(methodOverride());
app.use(cookieParser("secretsecretsecretsessioncode"));

app.set('trust proxy', true);
app.use(csrf({
  cookie: true
}));
app.use(session({
  secret: 'secretsecretsecretsessioncode',
  cookie: {
    maxAge: 12 * 60 * 60 * 1000, // 12 hours
    secure: true
  },
  proxy: true,
  saveUninitialized: true,
  resave: false,
  store: new mongoStore({
    mongooseConnection: mongo.db,
    autoReconnect: true,
    stringify: false
  })
}));
app.use(adldap_model.passport.initialize());
app.use(adldap_model.passport.session());

app.use(function (req, res, next) {
  res.locals.csrftoken = req.csrfToken();
  next();
});
```

**Comment by KaiserWolfTaco** [comment]
Moving this question to stackoverflow

**Comment by sawyerh** [comment]
@KaiserWolfTaco Our project has observed this as well, and are also scratching our heads. The recent pattern is that this mostly happens for mobile users (both Android Chrome and iOS Safari). Are you seeing any patterns in affected browsers?

**Comment by KaiserWolfTaco** [comment]
@sawyerh our issue is only on desktop browsers. We don't have mobile users.

**Comment by wallynm** [comment]
@KaiserWolfTaco , you had any update on this? We have similar problem where overall the CSRF always work, we can't find any error while testing but we get 20 errors related to CSRF for every 30mins at average. Still don't get what's happening

**Comment by wallynm** [comment]
One thing that i've spot at your code is that you're using cookie true config
```
app.use(csrf({
  cookie: true
}));
```

It should be set as false, as you're using mongodb-session

**Comment by Monokai** [comment]
I'm also seeing this. It looks like it happens mostly on Android, but not sure yet. I'm requesting a CSRF token just before I submit post requests. And that works fine most of the time. My setup looks a lot like the one from @KaiserWolfTaco (except I don't use `cookie: true`).

One thing I'm noticing though. When there's an error, it's usually 3 or more similar errors at roughly the same time. That also means these requests reach different servers (it's a containerized setup). But it shouldn't really matter, because sessions are saved in the database. Or maybe the client rapidly fires multiple requests for some reason?

It's really strange.
