### ISSUE TITLE
Hi, after several hours i have spend trying to resolve the invalid token in nestjs I try to get help here. 

### ISSUE THREAD

**Issue by jensysantana** [expressjs/csurf#248]
I hope i find some help here with my issue in nestjs. 

I have implemented the nestjs steps to use csurf but in POST request i have an error in return.

this is my rep: https://github.com/jensysantana/csrf-isssue

this is the error:

Application is running on: http://[::1]:43284
[Nest] 955  - 12/10/2021, 12:25:18 AM   ERROR [ExceptionsHandler] invalid csrf token
ForbiddenError: invalid csrf token
    at verifytoken (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/csurf/index.js:268:11)
    at csrf (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/csurf/index.js:96:7)
    at Layer.handle [as handle_request] (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/index.js:317:13)
    at /Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/index.js:317:13)
    at /Users/jackdaniel/Desktop/claford/accountServer/node_modules/express/lib/router/index.js:284:7

**Comment by dougwilson** [comment]
Hello, the issue is that you are using the wrong value to submit back. You can find our docs on SPA here: https://github.com/expressjs/csurf#single-page-application-spa

**Comment by jensysantana** [comment]
I have this error : TypeError: req.csrfToken is not a function

after add this code:
app.all('*', function (req, res) {
  res.cookie('XSRF-TOKEN', req.csrfToken())
 // res.render('index')
})

**Comment by dougwilson** [comment]
Hi, so that error would indicate that you attempted to use a function of this middleware before you used the middleware. Make sure you `app.use` any middleware before you try to use features that middleware provides so they are loaded.

**Comment by jensysantana** [comment]
ok. thank you. I was thinking the way nestjs handle the csurf was diferent then plain express app. but they work the same way.

first in my case using double submit so using the cookie method. in nestjs 

1.- create a method inside of a controller and then send the req.csrfToken() and store the csrf token. I use to use cookie to store i read in some post where they said is better to save the token in memory others choose localStorage etc.
so then set the token in the headers with one of the headers csurf support. so and then magic. it's work. 

I hope this help. and thank you.

**Comment by tokzy** [comment]
@jensysantana  can you please share your code on how you solve it?
