### ISSUE TITLE
cookie value different from csrfToken()

### ISSUE THREAD

**Issue by KevinMongiello** [expressjs/csurf#252]
Hi, I'm getting a different value set in the cookie than when i run `req.csrfToken()`. 

```js
app.use(cookieParser());
const csrfProtection = csrf({ cookie: true });
app.get('/api/form', csrfProtection, (req, res) => {
    const token = req.csrfToken();
    res.send({ csrfToken: token });
})
```

I'm manually setting the `_csrf` token as a workaround instead:
```js
const token = req.csrfToken();
res.cookie('_csrf', token);
res.send({ csrfToken: token });
```

Minimum reproducible repo: https://github.com/KevinMongiello/csurf-issue-sample

**Comment by dougwilson** [comment]
Hello, that is as design, as `req.csrfToken()` returns the csrf token to use when submitting requests, while the `cookie` option controls where the token secret is stored.

**Comment by KevinMongiello** [comment]
Yeah long story short I goofed.

Not sure why I was getting "invalid csrf token" for so long, but i seem to have it working now.  Thanks! (also very impressed by your reply time :D )

**Comment by dougwilson** [comment]
No problem; happy to help

**Comment by NOBHACKER120** [comment]
Hi GITHUB! I have a some issue from yesterday [*] 7067 Passwords loads successfully
[*] Do you want to use proxy (y/n): y

[*] Check new ip...
[*] Can't reach proxy "157.119.207.35:8080"

[*] Please add delay between the bruteforce action (in seconds): 1
                                                        Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection                                             raise err
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:                                             
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 994, in _prepare_proxy
    conn.connect()                                        File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn                                                         raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x708ae1dc90>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:                                             
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x708ae1dc90>: Failed to establish a new connection: [Errno 113] No route to host')))
                                                        During handling of the above exception, another exception occurred:
                                                        Traceback (most recent call last):
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 146, in <module>
    sess = instabrute.Login(password)
  File "/data/data/com.termux/files/home/alkrinsta/alkrinsta.py", line 105, in Login
    r = sess.get('https://www.instagram.com/')            File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/sessions.py", line 542, in get        return self.request('GET', url, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/sessions.py", line 529, in request    resp = self.send(prep, **send_kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)                   File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x708ae1dc90>: Failed to establish a new connection: [Errno 113] No route to host')))

CSRFTOKEN ISSUE HELP ME PLEASE 🙏
